### PR TITLE
Fix sort algorithm: singleton and differents separators

### LINKED ISSUE #650: Border case? : sorting a datatable with duplicate lines produces an invalid output file
#### Context
Prior to a multi-tables TrainPredictor (Root datatable + Additional datatable), we need to sort the tables.

In a specific customer case, the additional table contains duplicates (the whole line can be found many times).

In this case, the sort does not behave correctly :
- the process ends without any error
- but in the output file we have a mix of lines with tab separated fields (expected) and comma separated fields (this is the input format and is unexpected).

```
(base) thierry@thierry-precision5570:~/Khiops/HECTOR$ grep -v "," flash_360_pseudonymization.csv_sorted | head -3
id_client	box_type	device_mac	event_family	event_type	event_subtype	nb_event	duration
000031433	Livebox 6	5E:0F:39:5A:89:F5	Wifi	RSSI Faible < -75dB	Wifi 5GHz	1	0.0
000031433	Livebox 6	26:07:6E:FD:49:25	Wifi	SSW Handover	Wifi 2GHz	1	0.0
```
```
(base) thierry@thierry-precision5570:~/Khiops/HECTOR$ grep "," flash_360_pseudonymization.csv_sorted | head -3
200231285,Livebox 6,4F:1F:8D:92:49:A0,Wifi,Connexion equipement,Wifi 2GHz,1,0.0
200231285,Livebox 6,4F:1F:8D:92:49:A0,Wifi,Connexion equipement,Wifi 2GHz,1,0.0
200231285,Livebox 6,4F:1F:8D:92:49:A0,Wifi,Connexion equipement,Wifi 2GHz,1,0.0
```

The output file is thus not valid and will produce error later if given to khiops as an input file.

#### Questions/Ideas
Many hypothesis were tested to find the root cause but all were dead-ends so far
	- empty fields : (cf ,,) 
	- duration under the scientific notation ? : 5.7870370370370366E-5

The only way to avoid totally the problem is to remove duplication in this additional datatable.
```
sort flash_360_pseudonymization.csv|uniq > flash_360_pseudonymization_uniq.csv

```

**Should we ask the customer to preprocess his additional datatable to remove the duplicates ?**

### Additional information
- Khiops version 1.3.0

- the khiops dictionary (dictionnaire.kdic) - [dictionnaire.kdic.txt](https://github.com/user-attachments/files/19482198/dictionnaire.kdic.txt)
- the pre-processed additional datatable (flash_360_pseudonymization.csv) compressed with BZ2 : it was "pseudonymized-with-format-preserved" to hide the customer MSISDN and MAC address - too big unfortunately to be attached to this issue and the binary format is not supported.
- the khiops scenario (khiops_sort.txt) - [khiops_sort.txt](https://github.com/user-attachments/files/19482167/khiops_sort.txt)

)

### PR DESCRIPTION
**Pull request by bruno-at-orange**
The singleton chunks don't need to be sorted, but if the input and output file separators are different, they need to be rewritten to change the file separator.

The rewrite is handled in the slaveProcess: it is the same process used for the chunk to be sorted, the only difference being that the keys are not sorted if it is a singleton. This can be optimised, of course, but singletons are rare, and optimising would make the code (which is already big enough) more complex.

### CODE REVIEW

File: src/Learning/KWDataUtils/KWChunkSorterTask.cpp [hunk 1]
```diff
@@ -646,8 +646,12 @@ boolean KWChunkSorterTask::SlaveProcess()
 		// Tri des lignes extraites
 		if (bOk and not TaskProgression::IsInterruptionRequested())
 		{
-			oaKeyLines.SetCompareFunction(KWKeyLinePairCompare);
-			oaKeyLines.Sort();
+			// Si c'est un sigleton, on ne trie pas, on veut juste changer le separateur du fichier
```
Comment (marcboulle) [inline src/Learning/KWDataUtils/KWChunkSorterTask.cpp:649]: sigleton -> singleton

File: src/Learning/KWDataUtils/KWChunkSorterTask.cpp [hunk 2]
```diff
@@ -646,8 +646,12 @@ boolean KWChunkSorterTask::SlaveProcess()
...
+			if (not(input_bSingleton and shared_bSameSeparator))
```
Comment (marcboulle) [inline src/Learning/KWDataUtils/KWChunkSorterTask.cpp:650]: if (not input_bSingleton)

**Review by marcboulle — APPROVED** [review]
LGTM
Petite correction

File: src/Learning/KWDataUtils/KWChunkSorterTask.cpp (hunk 2 above)
Comment (bruno-at-orange) [reply src/Learning/KWDataUtils/KWChunkSorterTask.cpp:650]: done

File: src/Learning/KWDataUtils/KWChunkSorterTask.cpp (hunk 1 above)
Comment (bruno-at-orange) [reply src/Learning/KWDataUtils/KWChunkSorterTask.cpp:649]: done
