### PR TITLE
bug fix: remove chunks when interruption is requested inside concatenation

### LINKED ISSUE #466: Temporay files not cleaned in case of user interruption during worker finalisation in deployment task
#### Description
```
  J’ai déployé une grosse base et interrompu au milieu de la concaténation 
  Puis j’ai refait un déploiement et la j’ai une erreur dans la phase worker finalisation
   Deploy model O_C_filtered_by_parc
   error: Model deployment C:\...\O_C_filtered_by_parc.csv : Record 8395194 : Temporary file 19_T_O_C_filtered_by_parc.csv already exists in directory C:\...\Temp\~Khiops3_4
   error: Model deployment C:\...\O_C_filtered_by_parc.csv : Interrupted because of errors
```
 Analyse du problème
- bug lors d'une interruption utilisateur intervenant pendant le MasterFinalize de la tache de déploiement
  - la gestion de cette interruption utilisateur, et notament le nettoyage des fichier temporaire est probablement erronées
- problème non capturé par le scénario de CrashTest avec interruption utilisateur dans le MasterFinalize de la tache de déploiement
   - probablement parce que l'interruption par CrashTest est déclenchee avant le début de la concaténation
- correction probablement dans la méthode de concaténation
- étendre les possibilités des CrashTests? (pas forcément utile si trop coûteux à mettre en place)
- vérifier la correction si d'autres tâches utilise la concaténation de fichiers

### Context
- Khiops version: V10, V11
- Correction in V11, no need to backport correction to V10

### LINKED ISSUE #468: Fix minor bug in file concatenation in case of no selected field
#### Description
Bug mineur dans PLFileConcatenater:
- cas d'une base avec ligne d’entête, mais avec aucun champs sélectionné
  - on ne crée pas de ligne d'entete (vide) dans ce cas
  - ajouter des méthodes Set/GetHeaderLineUsed
  - écrire la ligne d’entête (meme vide) selon ce boolean, et non selon le nombre de champs du vecteur GetHeaderLine()
- tests dans LearningTest\TestKhiops\NewV10\DetectFileFormatSideEffects
  
### Context
- Khiops version: V10, V11
- Correction in V11, no need to backport correction to V10

### PR DESCRIPTION
**Pull request by bruno-at-orange**
A simple fix: temporary files are cleaned when there is an error. User interruption wasn't an error, it is  now.
closing #466 

2 extra things:
- Remove `bRemoveChunks` from the concatenate API , because it is always used with `bRemoveChunks=true`
- Reserve the size of the output file in concatenation.

Fix bug #468 
:warning: Don't forget to add a line in TestKhiops/NewV10/DetectFileFormatSideEffects/results.ref/D_NoFieldsHL.txt

### CODE REVIEW

**Review by marcboulle — CHANGES_REQUESTED** [review]
LGTM

Pour les deux questions, cela me semble pertinent de 
- supprimer le paramètre inutile bRemoveChunks
- implémenter la réserve de la taille

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp [hunk 1]
```diff
@@ -208,36 +209,69 @@ boolean PLFileConcatenater::Concatenate(const StringVector* svChunkURIs, const O
...
 			for (i = 0; i < svHeaderLine.GetSize(); i++)
 			{
-				if (i > 0)
-					outputBuffer.Write(cSep);
-				outputBuffer.WriteField(svHeaderLine.GetAt(i));
+				sField = svHeaderLine.GetAt(i);
+				lOutputFileSize += sField.GetLength();
 			}
-			outputBuffer.WriteEOL();
+			lOutputFileSize += svHeaderLine.GetSize() - 1;        // Les separateurs
```
Comment (marcboulle) [inline src/Parallel/PLParallelTask/PLFileConcatenater.cpp]: "svHeaderLine.GetSize() - 1" -> "max(0, svHeaderLine.GetSize() - 1)"
(effet de bord d'un fichier en sortie sans aucun champ, avec une ligne vide par record)

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp [hunk 2]
```diff
@@ -208,36 +209,69 @@ boolean PLFileConcatenater::Concatenate(const StringVector* svChunkURIs, const O
...
+		// Calcul de la taille du fichier de sortie
 		for (nChunkIndex = 0; nChunkIndex < svChunkURIs->GetSize(); nChunkIndex++)
 		{
 			sChunkURI = svChunkURIs->GetAt(nChunkIndex);
-
-			// Interruption ?
-			if (not bOk or TaskProgression::IsInterruptionRequested())
+			lChunkSize = PLRemoteFileService::GetFileSize(sChunkURI);
+			lOutputFileSize += lChunkSize;
+			if (lChunkSize == 0 and PLRemoteFileService::FileExists(sChunkURI))
```
Comment (marcboulle) [inline src/Parallel/PLParallelTask/PLFileConcatenater.cpp]: "and PLRemoteFileService::FileExists(sChunkURI)" -> "and **not** PLRemoteFileService::FileExists(sChunkURI)"

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp [hunk 3]
```diff
@@ -208,36 +209,69 @@ boolean PLFileConcatenater::Concatenate(const StringVector* svChunkURIs, const O
...
+			{
+				bOk = false;
+				if (errorSender != NULL)
+					errorSender->AddError("Missing chunk file : " + sChunkURI);
 				break;
+			}
+		}
```
Comment (marcboulle) [inline src/Parallel/PLParallelTask/PLFileConcatenater.cpp:255]: Ajouter un test d'interruption

if TaskProgression::IsInterruptionRequested())
{
  bOk = false;
  break;
}

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp [hunk 4]
```diff
@@ -208,36 +209,69 @@ boolean PLFileConcatenater::Concatenate(const StringVector* svChunkURIs, const O
...
-			if (PLRemoteFileService::FileExists(sChunkURI))
+			// Parcours de tous les chunks
+			for (nChunkIndex = 0; nChunkIndex < svChunkURIs->GetSize(); nChunkIndex++)
 			{
+				sChunkURI = svChunkURIs->GetAt(nChunkIndex);
+
+				// Interruption utilisateur ?
+				if (not bOk or TaskProgression::IsInterruptionRequested())
+					break;
+
```
Comment (marcboulle) [inline src/Parallel/PLParallelTask/PLFileConcatenater.cpp:289]: // Interruption utilisateur
if (TaskProgression::IsInterruptionRequested())
{
  bOk = false;
  break;
}

**Review by marcboulle — CHANGES_REQUESTED** [review]

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp (hunk 1 above)
Comment (bruno-at-orange) [reply src/Parallel/PLParallelTask/PLFileConcatenater.cpp]: done

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp (hunk 2 above)
Comment (bruno-at-orange) [reply src/Parallel/PLParallelTask/PLFileConcatenater.cpp]: done

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp (hunk 3 above)
Comment (bruno-at-orange) [reply src/Parallel/PLParallelTask/PLFileConcatenater.cpp:255]: done

File: src/Parallel/PLParallelTask/PLFileConcatenater.cpp (hunk 4 above)
Comment (bruno-at-orange) [reply src/Parallel/PLParallelTask/PLFileConcatenater.cpp:289]: done

**Review by marcboulle — APPROVED** [review]
LGTM
